import Head from "next/head";
// Style
import classes from "./style.module.less";

const propTypes = {};

const defaultProps = {};

const Index = ({}) => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Sharing Session</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome to The <a href="/">Sharing Session!</a>
        </h1>
      </main>

      <footer className={classes.footer}>
        Powered by :
        <span>
          <b> Team Sharing Session</b>
        </span>
      </footer>
    </div>
  );
};

Index.propTypes = propTypes;

Index.defaultProps = defaultProps;

export default Index;